site_name: Sam Rambles
site_url: https://samrambles.com
site_description: Technology Writing
site_author: Sumanth "Sam" Peddamatham
copyright: Made with ❤️ by Sam.
repo_name: peddamat/mkdocs-obsidian
repo_url: https://github.com/peddamat/mkdocs-obsidian
edit_uri: edit/main/docs/
docs_dir: ./notes
site_dir: ./site

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: white
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - header.autohide         # Hide header when scrolling down
    - search.share
    - search.highlight
    - search.suggest
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp2
<<<<<<< temp2
||||||| ancestor
=======
    - header.autohide
>>>>>>> Cleaned up homepage.
||||||| ancestor
    - header.autohide
=======
>>>>>>> Fixed homepage.
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tracking     # Reflect current #section in URL
    - navigation.top          # Back-to-top button
    - navigation.sections     # Expands sections in left-sidebar
    - navigation.tabs         # Sections in header
    - toc.integrate           # Moves toc from right sidebar to left
    # - navigation.instant
<<<<<<< temp
    - toc.follow
    # - toc.integrate
||||||| ancestor
=======
    # Added below
||||||| ancestor
    # Added below
=======
>>>>>>> Updating repository from testing environment.
||||||| ancestor
    # Added below
=======
>>>>>>> Updating repository from testing environment.
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tracking
    - navigation.top
    - navigation.sections
    # - navigation.instant
    - toc.follow
    # - toc.integrate
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
=======
    # Added below
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tracking
    - navigation.top
    - navigation.sections
    # - navigation.instant
    - toc.follow
    # - toc.integrate
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
    - toc.follow
    # - toc.integrate
=======
    # - toc.follow            # Doesn't seem to work
    # - navigation.path         # Breadcrumb above page title
>>>>>>> Fixed homepage.
  font:
    text: Noto Sans
    code: IMB Plex Mono

plugins:

  - roamlinks                 # Resolves Obsidian [[wikilinks]]
  - awesome-pages
  - git-revision-date         # Adds 'Last updated:' to pages
  - minify:
      minify_html: true
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp2
<<<<<<< temp2
  - roamlinks
||||||| ancestor
  - roamlinks
=======
  - tags:
      tags_file: tags.md
      # Below are insiders-only settings
      # tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower

  - search:
      prebuild_index: python  # Adds 100Kb to site
      indexing: titles
      separator: '[\s\-\.]+'
      lang:
        - en
>>>>>>> Cleaned up homepage.
  - blogging:
      dirs: # The directories to be included
        - .
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom

      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      categories:
        - name: reviews
          dirs:
            - reviews

      # GLOBAL CONFIG: configs apply to all categories
      time_format: '%d/%m/%y %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'
      features:
        tags:
          index_page: tags.md
          insert: top
||||||| ancestor
  - roamlinks
=======
  - ezlinks:
      wikilinks: true
      reference_links: true
||||||| ancestor
  - ezlinks:
      wikilinks: true
      reference_links: true
=======
  - roamlinks
>>>>>>> Updating repository from testing environment.
  - blogging:
      dirs: # The directories to be included
        - .
      template: overrides/custom-blog.html

      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      categories:
        - name: reviews
          dirs:
            - reviews

      # GLOBAL CONFIG: configs apply to all categories
      time_format: '%d/%m/%y %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'
      features:
        tags:
          index_page: tags.md
          insert: top
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
  - roamlinks
=======
  - ezlinks:
      wikilinks: true
      reference_links: true
||||||| ancestor
  - ezlinks:
      wikilinks: true
      reference_links: true
=======
  - roamlinks
>>>>>>> Updating repository from testing environment.
  - blogging:
      dirs: # The directories to be included
        - .
      template: overrides/custom-blog.html

      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      # categories:
      #   - name: reviews
      #     dirs:
      #       - reviews

      # GLOBAL CONFIG: configs apply to all categories
<<<<<<< temp
      time_format: '%d/%m/%y %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'
<<<<<<< temp
      features:
        tags:
          index_page: tags.md
          insert: top
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
      features:
        tags:
          index_page: tags.md
          insert: top
=======
      # features:
      #   tags:
      #     index_page: tags.md
      #     insert: top
>>>>>>> Cosmetic changes.
||||||| ancestor
      time_format: '%d/%m/%y %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'
      # features:
      #   tags:
      #     index_page: tags.md
      #     insert: top
=======
      time_format: '%m/%d/%y %H:%M:%S'
      meta_time_format: '%m/%d/%y %H:%M:%S'
>>>>>>> Cleaned up homepage.

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/peddamat
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peddamat

markdown_extensions:
  # Table of contents
  - toc:
      permalink: true
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp2
  # Added below
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
<<<<<<< temp
||||||| ancestor
=======
  # Added below
||||||| ancestor
  # Added below
=======
  # Source code boxes
  - pymdownx.superfences
  # Syntax highlighting
  - pymdownx.inlinehilite
>>>>>>> Cleaned up homepage.
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
<<<<<<< temp2
  # - mdx_wikilink_plus
  # - markdown.extensions.wikilinks
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
  # - mdx_wikilink_plus
  # - markdown.extensions.wikilinks
=======
>>>>>>> Updating repository from testing environment.
||||||| ancestor
=======
  # Added below
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # - mdx_wikilink_plus
  # - markdown.extensions.wikilinks
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
  # - mdx_wikilink_plus
  # - markdown.extensions.wikilinks
=======
>>>>>>> Updating repository from testing environment.

extra_css:
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp2
  - stylesheets/extra.css
  - stylesheets/hide_nav.css

hooks:
  - hooks/flatten_filenames.py
  - hooks/only_include_published.py
||||||| ancestor
  - stylesheets/extra.css
=======
  - stylesheets/extra.css
<<<<<<< temp2
>>>>>>> Cleared out original docs folder & added my vault.
||||||| ancestor
=======
  - stylesheets/hide_nav.css

hooks:
  - hooks/flatten_filenames.py
<<<<<<< temp2
  # - hooks/only_include_published.py
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
  # - hooks/only_include_published.py
=======
  - hooks/only_include_published.py
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
  - stylesheets/extra.css
=======
  - stylesheets/extra.css
<<<<<<< temp
>>>>>>> Cleared out original docs folder & added my vault.
||||||| ancestor
=======
  - stylesheets/hide_nav.css
||||||| ancestor
  - stylesheets/extra.css
  - stylesheets/hide_nav.css
=======
  - .stylesheets/extra.css
  - .stylesheets/hide_nav.css
>>>>>>> Updated stylesheets folder.
||||||| ancestor
  - .stylesheets/extra.css
  - .stylesheets/hide_nav.css
=======
  - stylesheets/extra.css
<<<<<<< temp
  - stylesheets/hide_nav.css
>>>>>>> Update mkdocs.yml
||||||| ancestor
  - stylesheets/hide_nav.css
=======
  # - stylesheets/hide_nav.css
>>>>>>> Fixed homepage.

hooks:
  - hooks/flatten_filenames.py
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp
<<<<<<< temp
  # - hooks/only_include_published.py
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
  # - hooks/only_include_published.py
=======
  - hooks/only_include_published.py
>>>>>>> Copied over changes from testing environment.
||||||| ancestor
  - hooks/only_include_published.py
=======
  - hooks/only_include_published.py
>>>>>>> Update mkdocs.yml
||||||| ancestor
  - hooks/only_include_published.py
=======
  - hooks/only_include_published.py
>>>>>>> Cleaned up homepage.
||||||| ancestor
  - hooks/only_include_published.py
=======
  - hooks/only_include_published.py
>>>>>>> Update and rename gh-pages.yml.off to gh-pages.yml Update gh-pages.yml Update requirements.txt Update gh-pages.yml Update mkdocs.yml Update gh-pages.yml Update gh-pages.yml Update gh-pages.yml Update gh-pages.yml Update gh-pages.yml Update mkdocs.yml Update gh-pages.yml Update gh-pages.yml Update and rename gh-pages.yml.off to gh-pages.yml Update gh-pages.yml Update requirements.txt Update gh-pages.yml Update mkdocs.yml Update gh-pages.yml Update gh-pages.yml Update gh-pages.yml Update gh-pages.yml Update gh-pages.yml Update mkdocs.yml Switching to pipenv.
