site_name: Sam Rambles
site_url: https://samrambles.com
site_description: Technology Writing
site_author: Sumanth "Sam" Peddamatham
copyright: Made with ❤️ by Sam.
repo_name: peddamat/mkdocs-obsidian
repo_url: https://github.com/peddamat/mkdocs-obsidian
edit_uri: edit/main/docs/
docs_dir: ./notes
site_dir: ./site

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: white
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - announce.dismiss        # Allows dismissing announcement banner
    - header.autohide         # Hide header when scrolling down
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.tracking     # Reflect current #section in URL
    - navigation.top          # Back-to-top button
    - navigation.sections     # Expands sections in left-sidebar
    - navigation.tabs         # Sections in header
    - navigation.indexes      # Index.htmls for sections
    # - toc.integrate           # Moves toc from right sidebar to left
    # - navigation.instant
    # - toc.follow            # Doesn't seem to work
    # - navigation.path         # Breadcrumb above page title
  font:
    text: Noto Sans
    code: IMB Plex Mono


plugins:
  - roamlinks                 # Resolves Obsidian [[wikilinks]]
  - awesome-pages
  - git-revision-date:        # Adds 'Last updated:' to pages
      repo_dir: "notes"
  - glightbox:                # Add glightbox image zoom plugin
      effect: none
      draggable: false
      slide_effect: none
  - mkdocs-video:             # Embedded video support
      css_style:
        width: "100%"
        height: "40vw"
  - minify:
      minify_html: true
  - tags:
      tags_file: tags.md
      # Below are insiders-only settings
      # tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower

  - search:
      # prebuild_index: python  # Adds 100Kb to site
      # indexing: titles
      separator: '[\s\-\.]+'
      lang:
        - en
  - blogging:
      dirs: # The directories to be included
        - Guides
        - Notes
        - Projects
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom

      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      categories:
        - name: guides
          template: overrides/custom-blog.html
          dirs:
            - Guides
        - name: notes
          template: overrides/custom-blog.html
          dirs:
            - Notes
        - name: projects
          template: overrides/custom-blog.html
          sort:
            from: old
          dirs:
            - Projects

      # GLOBAL CONFIG: configs apply to all categories
      time_format: '%b %-d, %Y'
      meta_time_format: '%m-%d-%Y'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/peddamat
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peddamat
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/speddamat

markdown_extensions:
  # Table of contents
  - toc:
      permalink: true
  # Collapsible admonitions
  - pymdownx.details
  # Source code boxes
  - pymdownx.superfences
  - pymdownx.tabbed:          # Tabs
      alternate_style: true
  # Syntax highlighting
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # MathJax support
  - pymdownx.arithmatex:
      generic: true

  - meta
  - admonition
  - attr_list                 # Allows adding {attributes} to images
  - md_in_html                # Allows adding {attributes} to images
  - def_list
  - footnotes
  - sane_lists

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - assets/stylesheets/extra.css
  # - assets/stylesheets/hide_nav.css

extra_javascript:
  # Required for MathJax support
  - assests/scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - hooks/flatten_filenames.py
  - hooks/only_include_published.py
