name: Build and Deploy Site

on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mkdocs-obsidian repo
        uses: actions/checkout@v3

      - name: Checkout notes repo into ./notes
        uses: actions/checkout@v3
        with:
          token:  ${{ secrets.PULL_NOTES }}
          repository: peddamat/notes
          path: notes

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

      - run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PULL_NOTES }}
          external_repository: peddamat/peddamat.github.io
          publish_branch: main  # default: gh-pages
          publish_dir: ./site
          cname: samrambles.com
